[package]
name = "tsk"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
clap_complete = "4"
edit = "0"
nix = { version = "0", features = ["fs"] }
thiserror = "1"
url = "2"
xattr = "1"
colored = "2"
smallstr = "0"
open = "5"

[build-dependencies]
clap_mangen = "0"
