[package]
name = "tsk-cli"
version = "0.2.3"
edition = "2021"
publish = true
license = "MIT"
license-file = "LICENSE"
description = "A command-line first, file-system based task manager"
repository = "https://codeberg.org/ngp/tsk"
homepage = "https://tsk.ngp.computer/"
readme = "readme"
authors = ["Noah Pederson <noah@packetlost.dev>"]

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
clap_complete = "4"
edit = "0"
nix = { version = "0", features = ["fs"] }
thiserror = "2"
url = "2"
xattr = "1"
colored = "2"
open = "5"
itertools = "0"

[build-dependencies]
clap_mangen = "0"
